### ISSUE TITLE
Broadcast not showing in client.

### ISSUE THREAD

**Issue by LuxusDarkangel** [trentech/SimpleBroadcast#1]
Using SimpleBroadcast with SpongeForge 5.0.0-BETA-1503 (latest). When I broadcast something, I can see it in the console but doesn't apper clientside.

**Comment by trentech** [comment]
This is probably due to a permissions problem.
simplebroadcast.off disables broadcasts for certain players. This will pose a problem if you give players op permissions. I'm planning on changing this in the future

**Comment by LuxusDarkangel** [comment]
Yep, that's actually the problem, you can't see the broadcasts as op.

**Comment by trentech** [comment]
Ok. I'll see if I can push an update later tonight

**Comment by trentech** [comment]
4b58ea38c050c60ecc80f8453d7996b2dd797874

**Comment by trentech** [comment]
I messed up

**Comment by trentech** [comment]
5835727232c5133fc42eaf4369b9588532bf3551
